[package]
name = "lx200-io"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = { version = "7.1.3", default-features = false }
thiserror = "2.0.11"

[dev-dependencies]
proptest = "1.6.0"

[features]
default = []
tokio = []
roms = []
